In [23]:
!pip install roboflow

In [24]:
!python3 -m pip install ultralytics==8.0.196

In [25]:
from roboflow import Roboflow

rf = Roboflow(api_key="4HVcvLNI3ZvJzGfLlZRs")
project = rf.workspace("test-dqo8y").project("forest-trees")
dataset = project.version(10).download("yolov8","./datasets/forest-trees")

loading Roboflow workspace...
loading Roboflow project...


In [26]:
from ultralytics import YOLO

In [162]:
model = YOLO("yolov8n.pt")

In [42]:
model.train( epochs=10,data="./datasets/data.yaml")

New https://pypi.org/project/ultralytics/8.1.6 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.196 🚀 Python-3.9.6 torch-2.1.2 CPU (Apple M2)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=../datasets/data.yaml, epochs=10, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=No

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x2a7549bb0>
fitness: 0.5875159794534048
keys: ['metrics/precision(B)', 'metrics/recall(B)', 'metrics/mAP50(B)', 'metrics/mAP50-95(B)']
maps: array([    0.55407])
names: {0: 'Tree'}
plot: True
results_dict: {'metrics/precision(B)': 0.8174909658043016, 'metrics/recall(B)': 0.8250452452902354, 'metrics/mAP50(B)': 0.8885124807337441, 'metrics/mAP50-95(B)': 0.5540719237555893, 'fitness': 0.5875159794534048}
save_dir: PosixPath('/Users/timofeyobraztsov/Desktop/projects/geoflare_model/runs/detect/train10')
speed: {'preprocess': 0.9835826026068794, 'inference': 160.27080217997232, 'loss': 6.64682099313447e-05, 'postprocess': 4.285010424527255}

In [222]:
from PIL import Image
import numpy as np

In [207]:
model = YOLO("best.pt")

In [252]:
img = Image.open("test3.png")

In [253]:
results = model(img)
img = np.asarray(img)



0: 384x640 18 Trees, 85.1ms
Speed: 7.6ms preprocess, 85.1ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)


In [254]:
!pip install opencv-python
import cv2

In [255]:
xyxys = []
confidences = []
classes = []

for result in results:
    boxes = result.boxes.cpu().numpy()
    # for xyxy in xyxys:
    #     cv2.rectangle(
    #         np.asarray(img), (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0, 255, 0), 2
    #     )
    xyxys.append(boxes.xyxy)
    confidences.append(boxes.conf)
    classes.append(boxes.cls)
    im=None
    for xyxy in xyxys[0]:
        print(xyxy)
        
        rected_img = cv2.rectangle(
           img,
            (int(xyxy[0]), int(xyxy[1])),
            (int(xyxy[2]), int(xyxy[3])),
            (0, 255, 0),
            3,
        )
        im_arr = cv2.cvtColor(rected_img, cv2.COLOR_RGBA2RGB)
        im_arr
        # convert back to Image object
        im = Image.fromarray(im_arr)
    im.show()

[     111.59      252.99      230.49      346.86]
[     224.82      368.67      315.12      448.71]
[     50.461      544.74      183.51      643.59]
[     71.579      334.74      186.15      438.06]
[     19.161      425.44      178.65      548.86]
[     217.96      544.33      324.46      644.62]
[     412.75      443.54      578.18      643.36]
[     1007.8      297.32      1086.2      356.21]
[     298.42      472.35      414.07      574.11]
[      454.7      247.22      536.35      329.85]
[     261.95      158.79      350.57      234.85]
[      524.8      253.25      640.12      340.73]
[     218.32      545.01      367.09      645.85]
[      189.9      322.41      269.06      393.61]
[     712.72      269.67       828.9      359.98]
[     833.45       303.1      921.87      373.03]
[        857       169.6      928.33      237.03]
[      731.4      284.62      829.25      356.02]
